folio-org/mod-copycat

descriptors/ModuleDescriptor-template.json
So that Okapi install will initialize it.
=> Declare that mod-copycat supports tenant interface

Dockerfile, README.md, checkstyle/folio_checks.xml, descriptors/ModuleDescriptor-template.json, doc/getting-started.md, pom.xml, ramls/copycattargetprofile.json, src/main/java/org/folio/copycat/JsonMarc.java, src/main/java/org/folio/copycat/RecordImporter.java, src/main/java/org/folio/copycat/RecordRetriever.java, src/main/java/org/folio/rest/impl/CopycatAPI.java, src/main/java/org/folio/rest/impl/CopycatImpl.java, src/main/java/org/folio/rest/impl/Init.java, src/test/java/org/folio/copycat/JsonMarcTest.java, src/test/java/org/folio/copycat/RecordImporterTest.java, src/test/java/org/folio/copycat/RecordRetrieverTest.java, src/test/java/org/folio/rest/impl/CopycatTest.java, src/test/java/org/folio/rest/impl/ImporterMock.java, src/test/java/org/folio/rest/impl/InitTest.java, src/test/resources/marc1.json
This connects fine with zcat.oclc.org and gets a single record out.
No real passwords are part of the code, though.
=> Integrate yaz4j

ramls/copycatprofile.json
=> Add `externalIdentifierType` and `enabled` fields

src/main/java/org/folio/copycat/RecordImporter.java, src/main/java/org/folio/rest/impl/CopycatImpl.java, src/test/java/org/folio/copycat/RecordImporterTest.java
This makes the job name be "copycat update" or "copycat import", instead of "OCLC - Default Update Instance"
=> copycat import/update with job

pom.xml, ramls/copycatprofile.json, src/main/java/org/folio/copycat/RecordImporter.java, src/main/java/org/folio/rest/impl/CopycatImpl.java, src/main/resources/reference-data/profiles/library-of-congress.json, src/main/resources/reference-data/profiles/oclc-worldcat.json, src/test/java/org/folio/rest/impl/ImporterMock.java, src/test/java/org/folio/rest/impl/WebServiceTest.java
These are *required* for mod-copycat to operate as these are no
longer part of the code itself. Update the reference data records
to use these. Add test that uses mod-copycat as web service.
=> Extend with {create,update}JobProfileId MODCPCT-14

src/main/java/org/folio/copycat/RecordImporter.java, src/main/java/org/folio/rest/impl/CopycatImpl.java, src/test/java/org/folio/copycat/RecordImporterTest.java
With MODDATAIMP-370 the name is thrown away (ignored). This makes the work here simpler. It's really just a matter of throwing code away.
=> Do not set data import profile name MODCPCT-22

doc/getting-started.md
Thx to Maksym Sinichenko for pointing out.
=> Fix typo in curl invocation

src/test/java/org/folio/rest/impl/WebServiceTest.java
Test that "authentication" can be set and that upgrade with
reference data does not tamper with that.
=> Test module upgrade with reference data

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/copycat/RecordImporter.java, src/test/java/org/folio/rest/impl/ImporterMock.java
Major change of SRS API..  Depend on later interfaces and do necessary code change.
=> Update for recordType change MODCPCT-43 MODCPCT-44

NEWS.md, pom.xml
This time it mentions MODCPCT-39
=> Release 1.0.4

Dockerfile, Jenkinsfile, NEWS.md, pom.xml
=> Release 1.0.5

Dockerfile, Jenkinsfile, NEWS.md, pom.xml
https://issues.folio.org/browse/MODCPCT-55
Juniper/Kiwi hot fix
=> Upgrade to 1.1.2 MODCPCT-55

.editorconfig, README.md, ramls/copycatprofile.json, src/main/java/org/folio/copycat/RecordRetriever.java, src/test/java/org/folio/copycat/RecordRetrieverTest.java
https://issues.folio.org/browse/MODCPCT-60
=> Configurable marc encoding MODCPCT-60

descriptors/ModuleDescriptor-template.json
jq -r '.permissionSets[].displayName'
CopyCat - import records from remote resource
CopyCat - get CopyCat profiles
CopyCat - create CopyCat profile
CopyCat - get CopyCat profile
CopyCat - update CopyCat profile
CopyCat - delete CopyCat profile
CopyCat - all profile operations
CopyCat - all permissions
=> Update permission descriptions MODCPCT-59

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/rest/impl/CopycatImpl.java, src/test/java/org/folio/rest/impl/CopycatTest.java
Upgrade to RMB 33.2.5 - with raml-util updates.
=> Upgrade to RMB 33.2.5, Vert.x 4.2.4 MODCPCT-61

Dockerfile, src/main/java/org/folio/copycat/RecordRetriever.java
https://issues.folio.org/browse/MODCPCT-63
=> Log Z39.50 retrieval time MODCPCT-63

NEWS.md, pom.xml
Note next snapshot is 1.2.1-SNAPSHOT
=> Release 1.2.0 MODCPCT-62

NEWS.md, pom.xml
Bug fix release. Master branch is bug fix release branch as well.
=> Release 1.2.1 MODCPCT-65

descriptors/ModuleDescriptor-template.json, ramls/copycatimports.json, ramls/copycatprofile.json, src/main/java/org/folio/rest/impl/CopycatImpl.java, src/main/java/org/folio/rest/impl/exceptions/UnsupportedJobProfileException.java, src/test/java/org/folio/rest/impl/CopycatTest.java
Allowing importing single records with selected jobProfile
Jira: https://issues.folio.org/browse/MODCPCT-71
=> [MODCPCT-71] Allow importing single records with selected jobProfile

descriptors/ModuleDescriptor-template.json, ramls/copycatimports.json, ramls/copycatprofile.json, src/main/java/org/folio/rest/impl/CopycatImpl.java, src/main/java/org/folio/rest/impl/exceptions/UnsupportedJobProfileException.java, src/main/resources/reference-data/profiles/library-of-congress.json, src/main/resources/reference-data/profiles/oclc-worldcat.json, src/main/resources/templates/db_scripts/schema.json, src/main/resources/templates/db_scripts/update_profile.sql, src/test/java/org/folio/rest/impl/CopycatTest.java
Allowing importing with the selected job profile, created migration script for new fields, adjusted tests
=> Allow importing single record with selected jobProfile
